"""add historical weather observations table

Revision ID: b8975f126305
Revises: d31a32076841
Create Date: 2026-08-06 19:20:10.578959
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b8975f126305"
down_revision: str | None = "d31a32076841"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "historical_weather_observations",
        sa.Column("historical_weather_id", sa.UUID(), nullable=False),
        sa.Column("mlb_game_pk", sa.Integer(), nullable=False),
        sa.Column("game_date", sa.Date(), nullable=False),
        sa.Column("venue_mlb_id", sa.Integer(), nullable=True),
        sa.Column("condition", sa.String(), nullable=True),
        sa.Column("temp_f", sa.Numeric(), nullable=True),
        sa.Column("wind_mph", sa.Numeric(), nullable=True),
        sa.Column("wind_detail", sa.String(), nullable=True),
        sa.Column("capture_mode", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("backfill_run_id", sa.String(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["backfill_run_id"],
            ["backfill_runs.backfill_run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
        ),
        sa.PrimaryKeyConstraint("historical_weather_id"),
        sa.UniqueConstraint("mlb_game_pk"),
    )
    op.create_index(
        "ix_historical_weather_observations_game_date",
        "historical_weather_observations",
        ["game_date"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(
        "ix_historical_weather_observations_game_date", table_name="historical_weather_observations"
    )
    op.drop_table("historical_weather_observations")
    # ### end Alembic commands ###
