"""add probability_push to projections

Revision ID: d71edca7eb30
Revises: b8975f126305
Create Date: 2026-08-06 20:40:38.409279
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d71edca7eb30"
down_revision: str | None = "b8975f126305"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projections", sa.Column("probability_push", sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projections", "probability_push")
    # ### end Alembic commands ###
