"""initial schema

Revision ID: f4b13ecb5ad7
Revises:
Create Date: 2026-08-04 17:35:37.791906
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f4b13ecb5ad7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# ADR 0001 / CLAUDE.md non-negotiable #3: published records are append-only.
# Empirically verified (see commit history) that Postgres REVOKE genuinely
# restricts even the table *owner* -- no separate app role is needed. The
# same connection the app uses for INSERT/SELECT is structurally unable to
# UPDATE or DELETE these rows once this migration applies.
IMMUTABLE_TABLES = [
    "raw_schedule_events",
    "raw_probable_pitchers",
    "raw_lineups",
    "raw_pitcher_game_logs",
    "raw_weather_observations",
    "raw_park_factors",
    "raw_umpire_assignments",
    "raw_lines",
    "raw_final_box_scores",
    "projections",
    "grades",
    "audit_events",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=True),
        sa.Column("entity_id", sa.String(), nullable=True),
        sa.Column("run_id", sa.String(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_table(
        "feature_sets",
        sa.Column("feature_set_version", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("feature_set_version"),
    )
    op.create_table(
        "games",
        sa.Column("game_id", sa.String(), nullable=False),
        sa.Column("mlb_game_pk", sa.Integer(), nullable=True),
        sa.Column("game_date", sa.DateTime(), nullable=False),
        sa.Column("scheduled_start_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("home_team_id", sa.String(), nullable=True),
        sa.Column("away_team_id", sa.String(), nullable=True),
        sa.Column("venue_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("game_id"),
        sa.UniqueConstraint("mlb_game_pk"),
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("slate_date", sa.Date(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_stage", sa.String(), nullable=True),
        sa.CheckConstraint("status IN ('running', 'succeeded', 'failed')", name="ck_pipeline_runs_status"),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "players",
        sa.Column("player_id", sa.String(), nullable=False),
        sa.Column("mlb_person_id", sa.Integer(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("bats", sa.String(), nullable=True),
        sa.Column("throws", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("player_id"),
        sa.UniqueConstraint("mlb_person_id"),
    )
    op.create_table(
        "snapshots",
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("slate_date", sa.Date(), nullable=False),
        sa.Column("cutoff_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.CheckConstraint("status IN ('building', 'frozen', 'failed')", name="ck_snapshots_status"),
        sa.PrimaryKeyConstraint("snapshot_id"),
    )
    op.create_table(
        "source_health",
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("source_id"),
    )
    op.create_table(
        "sources",
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("adapter_version", sa.String(), nullable=True),
        sa.Column("base_url", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('schedule', 'pitcher_stats', 'weather', 'park', 'umpire', 'lines')",
            name="ck_sources_kind",
        ),
        sa.PrimaryKeyConstraint("source_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "teams",
        sa.Column("team_id", sa.String(), nullable=False),
        sa.Column("mlb_team_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("abbreviation", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("team_id"),
        sa.UniqueConstraint("mlb_team_id"),
    )
    op.create_table(
        "venues",
        sa.Column("venue_id", sa.String(), nullable=False),
        sa.Column("mlb_venue_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("park_factor_key", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("venue_id"),
        sa.UniqueConstraint("mlb_venue_id"),
    )
    op.create_table(
        "feature_values",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.String(), nullable=False),
        sa.Column("game_id", sa.String(), nullable=False),
        sa.Column("feature_set_version", sa.String(), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["feature_set_version"],
            ["feature_sets.feature_set_version"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["snapshots.snapshot_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pipeline_run_stages",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("detail", sa.String(), nullable=True),
        sa.CheckConstraint(
            "stage IN ('INGEST', 'VALIDATE', 'FREEZE', 'PROJECT', 'REVIEW', 'PUBLISH', 'GRADE')",
            name="ck_pipeline_run_stages_stage",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed', 'skipped')",
            name="ck_pipeline_run_stages_status",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pipeline_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "stage"),
    )
    op.create_table(
        "projections",
        sa.Column("projection_id", sa.String(), nullable=False),
        sa.Column("logical_key", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("supersedes_projection_id", sa.String(), nullable=True),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sport", sa.String(), nullable=False),
        sa.Column("market", sa.String(), nullable=False),
        sa.Column("player_id", sa.String(), nullable=False),
        sa.Column("game_id", sa.String(), nullable=False),
        sa.Column("line", sa.Numeric(), nullable=True),
        sa.Column("projection_mean", sa.Numeric(), nullable=True),
        sa.Column("projection_sd", sa.Numeric(), nullable=True),
        sa.Column("probability_over", sa.Numeric(), nullable=True),
        sa.Column("probability_under", sa.Numeric(), nullable=True),
        sa.Column("decision", sa.String(), nullable=False),
        sa.Column("decision_status", sa.String(), nullable=False),
        sa.Column("reason_codes", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("model_version", sa.String(), nullable=True),
        sa.Column("feature_set_version", sa.String(), nullable=True),
        sa.Column("decision_policy_version", sa.String(), nullable=True),
        sa.Column("source_snapshot_id", sa.UUID(), nullable=True),
        sa.Column("reproducibility_hash", sa.String(), nullable=True),
        sa.Column("git_commit_sha", sa.String(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_late_publication", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("decision IN ('OVER', 'UNDER', 'NO_PLAY')", name="ck_projections_decision"),
        sa.CheckConstraint(
            "decision_status IN ('QUALIFIED', 'UNCERTAIN', 'HELD', 'REJECTED')",
            name="ck_projections_decision_status",
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.game_id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.player_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["snapshots.snapshot_id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_projection_id"],
            ["projections.projection_id"],
        ),
        sa.PrimaryKeyConstraint("projection_id"),
        sa.UniqueConstraint("logical_key", "version", name="uq_projections_logical_key_version"),
    )
    op.create_table(
        "raw_final_box_scores",
        sa.Column("raw_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("mlb_game_pk", sa.Integer(), nullable=False),
        sa.Column("player_mlb_id", sa.Integer(), nullable=False),
        sa.Column("strikeouts_recorded", sa.Integer(), nullable=True),
        sa.Column("innings_pitched", sa.Numeric(), nullable=True),
        sa.Column("pitch_count", sa.Integer(), nullable=True),
        sa.Column("game_status", sa.String(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
        ),
        sa.PrimaryKeyConstraint("raw_id"),
    )
    op.create_index(
        "ix_raw_final_box_scores_pk_player_ingested",
        "raw_final_box_scores",
        ["mlb_game_pk", "player_mlb_id", "ingested_at"],
        unique=False,
    )
    op.create_table(
        "raw_lines",
        sa.Column("raw_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("mlb_game_pk", sa.Integer(), nullable=False),
        sa.Column("player_mlb_id", sa.Integer(), nullable=False),
        sa.Column("market", sa.String(), nullable=False),
        sa.Column("line", sa.Numeric(), nullable=False),
        sa.Column("over_price", sa.Numeric(), nullable=True),
        sa.Column("under_price", sa.Numeric(), nullable=True),
        sa.Column("is_suspended", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("record_hash", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
        ),
        sa.PrimaryKeyConstraint("raw_id"),
    )
    op.create_index(
        "ix_raw_lines_pk_player_ingested",
        "raw_lines",
        ["mlb_game_pk", "player_mlb_id", "ingested_at"],
        unique=False,
    )
    op.create_table(
        "raw_lineups",
        sa.Column("raw_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("mlb_game_pk", sa.Integer(), nullable=False),
        sa.Column("team_mlb_id", sa.Integer(), nullable=False),
        sa.Column("batting_order", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_confirmed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
        ),
        sa.PrimaryKeyConstraint("raw_id"),
    )
    op.create_index("ix_raw_lineups_pk_ingested", "raw_lineups", ["mlb_game_pk", "ingested_at"], unique=False)
    op.create_table(
        "raw_park_factors",
        sa.Column("raw_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("venue_id", sa.String(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("k_factor", sa.Numeric(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
        ),
        sa.PrimaryKeyConstraint("raw_id"),
    )
    op.create_index(
        "ix_raw_park_factors_venue_season_ingested",
        "raw_park_factors",
        ["venue_id", "season", "ingested_at"],
        unique=False,
    )
    op.create_table(
        "raw_pitcher_game_logs",
        sa.Column("raw_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("player_mlb_id", sa.Integer(), nullable=False),
        sa.Column("mlb_game_pk", sa.Integer(), nullable=True),
        sa.Column("stat_date", sa.DateTime(), nullable=False),
        sa.Column("batters_faced", sa.Integer(), nullable=True),
        sa.Column("strikeouts", sa.Integer(), nullable=True),
        sa.Column("pitch_count", sa.Integer(), nullable=True),
        sa.Column("innings_pitched", sa.Numeric(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
        ),
        sa.PrimaryKeyConstraint("raw_id"),
    )
    op.create_index(
        "ix_raw_pitcher_game_logs_player_ingested",
        "raw_pitcher_game_logs",
        ["player_mlb_id", "ingested_at"],
        unique=False,
    )
    op.create_table(
        "raw_probable_pitchers",
        sa.Column("raw_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("mlb_game_pk", sa.Integer(), nullable=False),
        sa.Column("player_mlb_id", sa.Integer(), nullable=False),
        sa.Column("team_mlb_id", sa.Integer(), nullable=True),
        sa.Column("is_confirmed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("record_hash", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
        ),
        sa.PrimaryKeyConstraint("raw_id"),
    )
    op.create_index(
        "ix_raw_probable_pitchers_pk_ingested",
        "raw_probable_pitchers",
        ["mlb_game_pk", "ingested_at"],
        unique=False,
    )
    op.create_table(
        "raw_schedule_events",
        sa.Column("raw_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("mlb_game_pk", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("record_hash", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
        ),
        sa.PrimaryKeyConstraint("raw_id"),
    )
    op.create_index(
        "ix_raw_schedule_events_pk_ingested",
        "raw_schedule_events",
        ["mlb_game_pk", "ingested_at"],
        unique=False,
    )
    op.create_table(
        "raw_umpire_assignments",
        sa.Column("raw_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("mlb_game_pk", sa.Integer(), nullable=False),
        sa.Column("umpire_name", sa.String(), nullable=True),
        sa.Column("is_available", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
        ),
        sa.PrimaryKeyConstraint("raw_id"),
    )
    op.create_index(
        "ix_raw_umpire_pk_ingested", "raw_umpire_assignments", ["mlb_game_pk", "ingested_at"], unique=False
    )
    op.create_table(
        "raw_weather_observations",
        sa.Column("raw_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("venue_id", sa.String(), nullable=False),
        sa.Column("forecast_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("temp_f", sa.Numeric(), nullable=True),
        sa.Column("wind_mph", sa.Numeric(), nullable=True),
        sa.Column("wind_dir", sa.String(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
        ),
        sa.PrimaryKeyConstraint("raw_id"),
    )
    op.create_index(
        "ix_raw_weather_venue_ingested", "raw_weather_observations", ["venue_id", "ingested_at"], unique=False
    )
    op.create_table(
        "snapshot_data_quality",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("check_name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("reason_code", sa.String(), nullable=True),
        sa.Column("detail", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("status IN ('pass', 'fail', 'warn')", name="ck_snapshot_dq_status"),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["snapshots.snapshot_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "snapshot_raw_refs",
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("raw_table", sa.String(), nullable=False),
        sa.Column("raw_id", sa.UUID(), nullable=False),
        sa.Column("natural_key", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["snapshots.snapshot_id"],
        ),
        sa.PrimaryKeyConstraint("snapshot_id", "raw_table", "raw_id"),
    )
    op.create_table(
        "grades",
        sa.Column("grade_id", sa.UUID(), nullable=False),
        sa.Column("projection_id", sa.String(), nullable=False),
        sa.Column("graded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("result", sa.String(), nullable=False),
        sa.Column("actual_strikeouts", sa.Integer(), nullable=True),
        sa.Column("final_box_score_raw_id", sa.UUID(), nullable=True),
        sa.Column("detail", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("result IN ('WIN', 'LOSS', 'PUSH', 'VOID', 'NO_PLAY')", name="ck_grades_result"),
        sa.ForeignKeyConstraint(
            ["final_box_score_raw_id"],
            ["raw_final_box_scores.raw_id"],
        ),
        sa.ForeignKeyConstraint(
            ["projection_id"],
            ["projections.projection_id"],
        ),
        sa.PrimaryKeyConstraint("grade_id"),
    )
    # ### end Alembic commands ###

    # Manual addition (not autogenerated): enforce append-only immutability
    # at the database level for the current connection role. See ADR 0001
    # and CLAUDE.md's do-not-do list -- if application code ever needs an
    # UPDATE/DELETE against one of these tables, the design is wrong, not
    # this grant.
    current_user = op.get_bind().engine.url.username
    for table in IMMUTABLE_TABLES:
        op.execute(f'REVOKE UPDATE, DELETE ON "{table}" FROM "{current_user}"')


def downgrade() -> None:
    current_user = op.get_bind().engine.url.username
    for table in IMMUTABLE_TABLES:
        op.execute(f'GRANT UPDATE, DELETE ON "{table}" TO "{current_user}"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("grades")
    op.drop_table("snapshot_raw_refs")
    op.drop_table("snapshot_data_quality")
    op.drop_index("ix_raw_weather_venue_ingested", table_name="raw_weather_observations")
    op.drop_table("raw_weather_observations")
    op.drop_index("ix_raw_umpire_pk_ingested", table_name="raw_umpire_assignments")
    op.drop_table("raw_umpire_assignments")
    op.drop_index("ix_raw_schedule_events_pk_ingested", table_name="raw_schedule_events")
    op.drop_table("raw_schedule_events")
    op.drop_index("ix_raw_probable_pitchers_pk_ingested", table_name="raw_probable_pitchers")
    op.drop_table("raw_probable_pitchers")
    op.drop_index("ix_raw_pitcher_game_logs_player_ingested", table_name="raw_pitcher_game_logs")
    op.drop_table("raw_pitcher_game_logs")
    op.drop_index("ix_raw_park_factors_venue_season_ingested", table_name="raw_park_factors")
    op.drop_table("raw_park_factors")
    op.drop_index("ix_raw_lineups_pk_ingested", table_name="raw_lineups")
    op.drop_table("raw_lineups")
    op.drop_index("ix_raw_lines_pk_player_ingested", table_name="raw_lines")
    op.drop_table("raw_lines")
    op.drop_index("ix_raw_final_box_scores_pk_player_ingested", table_name="raw_final_box_scores")
    op.drop_table("raw_final_box_scores")
    op.drop_table("projections")
    op.drop_table("pipeline_run_stages")
    op.drop_table("feature_values")
    op.drop_table("venues")
    op.drop_table("teams")
    op.drop_table("sources")
    op.drop_table("source_health")
    op.drop_table("snapshots")
    op.drop_table("players")
    op.drop_table("pipeline_runs")
    op.drop_table("games")
    op.drop_table("feature_sets")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
